### ISSUE TITLE
raspberry pi/ python version 

### ISSUE THREAD

**Issue by Austinthemighty** [adafruit/Adafruit_TSL2591_Library#10]
Is there a raspberry pi version available of the tsl2591

**Comment by DonBower** [comment]
This is a necessity for our Eclipse 2017 project

**Comment by ladyada** [comment]
hiya - there is not one at this time, nor an ETA for when we will have one done

**Comment by DonBower** [comment]
Thanks for the super fast response.
It looks like someone gave me a good starting point:
https://github.com/maxlklaxl/python-tsl2591
So I'm moving forward with the project.
I'll keep you posted.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ladyada** [comment]
hiya we've got a plan to do a TSL2591 driver for circuitpython - if you subscribe to
https://github.com/adafruit/circuitpython/issues/523
you'll get notified
(closing this one for now :)
