### ISSUE TITLE
Serial.print of Thresholds with wrong values in tsl2591_interrupt.ino

### ISSUE THREAD

**Issue by haku15** [adafruit/Adafruit_TSL2591_Library#11]
In the example "tsl2591_interrupt.ino" the  code

`Serial.print("Interrupt Threshold Window: -");
Serial.print(TLS2591_INT_THRESHOLD_LOWER, DEC);
Serial.print(" to +");

Serial.println(TLS2591_INT_THRESHOLD_LOWER, DEC);  
Serial.println("");`
has two minor mistakes:
1) the signs - and + should be removed, because the thresholds are from value X to value Y.
2) The second value printed should be TLS2591_INT_THRESHOLD_UPPER. The current code prints twice the lower threshold.

**Comment by ladyada** [comment]
thank u! fixed!
