### ISSUE TITLE
Inaccurate sensor information

### ISSUE THREAD

**Issue by NuclearPhoenixx** [adafruit/Adafruit_TSL2591_Library#22]
Hi,

I just found out that together with the Adafruit Unified Sensor API, this sensor reports back inaccurate data, like a minimum value of `0.0` when it should really be more like `0.000118`.

https://github.com/adafruit/Adafruit_TSL2591_Library/blob/608b3a2460f8f0c6e2c206f2116303c0568214f6/Adafruit_TSL2591.cpp#L484

And also the resolution seems to not be correct :thinking: 

https://github.com/adafruit/Adafruit_TSL2591_Library/blob/608b3a2460f8f0c6e2c206f2116303c0568214f6/Adafruit_TSL2591.cpp#L485

**Comment by Phoenix1747** [comment]
Any thoughts on this?

**Comment by caternuson** [comment]
Where does `0.000118` come from? How are you reading back `min_value`? Why is the resolution incorrect?

**Comment by Phoenix1747** [comment]
- The min/max values come from the Adafruit website https://www.adafruit.com/product/1980

> Compared to low cost CdS cells, this sensor is more precise, allowing for exact lux calculations and can be configured for different gain/timing ranges to detect **light ranges from 188 uLux up to 88,000 Lux** on the fly.

- You can print all the information with this function:
https://github.com/adafruit/Adafruit_TSL2591_Library/blob/bc80d5ee6827f8c2a832023a9204db21184bf5e0/Adafruit_TSL2591.cpp#L471

- The resolution seems incorrect because if it's really 1mLx then the value for `min_value` of 118uLx would be completely useless.

**Comment by caternuson** [comment]
That's probably indicating the minimum detectable lux. Zero lux will still be zero, so the minimum output is zero.

The driver doesn't actually use any of those parameters internally. They're more like meta data about the sensor. How are you using them in your application?

**Comment by Phoenix1747** [comment]
Don't know about the min lux limit...

Anyways, of course I know it's meta data and I'm not really using it for any real code, but it would be nice if those values actually reflected the real ones. And I'm not really sure anymore what's the correct data anymore.

**Comment by caternuson** [comment]
Are you getting bad readings using the library read functions? Like shown in the example?
https://github.com/adafruit/Adafruit_TSL2591_Library/blob/master/examples/tsl2591/tsl2591.ino

**Comment by Phoenix1747** [comment]
As I said, since this is meta data this has nothing to do with the reading themselves. This is just about the documentation part.

**Comment by caternuson** [comment]
Closing for now. Can re-open if these values are creating an issue. The actual datasheet information on what these should be is lacking.

**Comment by NuclearPhoenixx** [comment]
You're right with the datasheet, but it would be nice if the values in the software at least reflect the value that you use to promote the sensor on your website i.e. `sensor->min_value=0.000188`. It's very confusing to see the values online and then see completely different ones in the software.
