### ISSUE TITLE
Confusing defines 

### ISSUE THREAD

**Issue by peekpt** [adafruit/Adafruit_TSL2591_Library#3]
- wrong constants in the code.
void simpleRead(void)
{
  // Simple data read example. Just read the infrared, fullspecrtrum diode 
  // or 'visible' (difference between the two) channels.
  // This can take 100-600 milliseconds! Uncomment whichever of the following you want to read
  uint16_t x = tsl.getLuminosity(TSL2591_VISIBLE);
  //uint16_t x = tsl.getLuminosity(**TSL2561**_FULLSPECTRUM);
  //uint16_t x = tsl.getLuminosity(**TSL2561**_INFRARED);

  Serial.print("[ "); Serial.print(millis()); Serial.print(" ms ] ");
  Serial.print("Luminosity: ");
  Serial.println(x, DEC);
}

**Comment by tdicola** [comment]
Oh nice thanks for finding the typo and raising the issue--just fixed it up.  Thanks!
