### ISSUE TITLE
Error compiling for board Arduino Nano 33 BLE

### ISSUE THREAD

**Issue by bergstar** [adafruit/Adafruit_TSL2591_Library#36]
- Arduino board:  Arduino Nano 33 BLE

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.11

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): 
Select target board and try to compile:
```
#include <Wire.h>
#include <Adafruit_Sensor.h>
#include "Adafruit_TSL2591.h"
```
Following error dump will be given:
```
Alternatives for avr/pgmspace.h: []
ResolveLibrary(avr/pgmspace.h)
C:\Users\Arduino\Documents\Arduino\libraries\Adafruit_TSL2591_Library\Adafruit_TSL2591.cpp:50:12: fatal error: avr/pgmspace.h: No such file or directory
  -> candidates: []

   #include <avr/pgmspace.h>

            ^~~~~~~~~~~~~~~~

compilation terminated.
```

File is currently located under deprecated-avr-comp:
https://github.com/arduino/ArduinoCore-API/blob/master/api/deprecated-avr-comp/avr/pgmspace.h

Current solution is to make a local copy of this library and copy inn deprecated file.

**Comment by ladyada** [comment]
try latest 'master' branch, we'll update later in manager
