### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by rajdarge** [adafruit/Adafruit_TSL2591_Library#5]
The TSL2591 is special because it can read to low light level (188microlux). there are a few problems with the Universal sensor definition: 
sensor -> resolution = 0.0001 (currently = 1.0)

Also the calculateLux function is set to a uint32_t when it should be a float (currently it tuncates the result to an integer). 
even with these changes though event.light still truncates the value to 2 decimal places. I can't seem to figure out why.

**Comment by ladyada** [comment]
done!
